### ISSUE TITLE
Possible repo transfer

### ISSUE THREAD

**Issue by NexiusTailer** [NexiusTailer/MapFix#7]
Hey. As the author of this script, I have never been against third-party publishing it on github due to the lack of my own repo here, but since the samp forum is now closed, I would like to ask for the transfer of this repository under my maintenance for a more convenient update in the future and easier search for users so that they don't have to look for it in the web archive on the forum and they'll find it in my profile on github instead.

**Comment by Southclaws** [comment]
Great!

Unfortunately GitHub is not allowing it at the moment so I'll give it another try tomorrow:

```
 You can only transfer a repository from an organization to yourself at this time 
```

**Comment by Southclaws** [comment]
I requested a transfer from my personal account.
