### ISSUE TITLE
Boxes reduced draw distance

### ISSUE THREAD

**Issue by ZantetsukenGT** [NexiusTailer/MapFix#8]
It happens both on samp and open.mp and either with and without the streamer plugin, their draw distance is greatly reduced to like 20 units

![1](https://user-images.githubusercontent.com/25725331/179437742-34812f47-7768-4602-b4ea-37b776005fe1.png)
![2](https://user-images.githubusercontent.com/25725331/179437748-dbbab6ca-1c26-469c-8dba-789b893ed2de.png)

**Comment by NexiusTailer** [comment]
MapFix ain't fixing game objects with low draw distance, flickering or incorrectly rendering in any other way. It only tries to fix those places where there is no collision but there is a texture, just creating invisible object(s) with similar collision shape inside this texture so the "broken" object become with collision.

This case is not fit for these actions.

**Comment by ZantetsukenGT** [comment]
I'll try to record a quick video after work

**Comment by ZantetsukenGT** [comment]
https://youtu.be/Ct0_vFvOKKM

**Comment by NexiusTailer** [comment]
So, this is not truly mapfix case since it just fixes "collision holes" in existing objects.
